platform=android
AndroidDevice=Pixel 9 Pro
AndroidBuildPath=src/test/resources/builds/Hamburger-testtag.apk


#platform=ios
iOSDevice=iPhone 16 Plus
iOSPlatformVersion=18.5
iOSBuildPath=/Users/zopsmart/Desktop/Eazyupdates.app
