name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-tests:
    runs-on: macos-13

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Appium
        run: |
          npm install -g appium@2.0.0
          appium -v
          appium driver install uiautomator2
          appium driver list --installed

      - name: Start Appium Server
        run: |
          nohup appium --port 4723 --log-level info > appium.log 2>&1 &
          sleep 5
          echo "Appium server started"

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd mobile-automation && mvn clean test