name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android-tests:
    runs-on: macos-13

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Build the Android APK first
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Android APK
        run: ./gradlew assembleDebug

      # Create the expected directory structure and copy APK
      - name: Prepare APK for tests
        run: |
          mkdir -p mobile-automation/src/test/resources/builds/
          cp app/build/outputs/apk/debug/app-debug.apk mobile-automation/src/test/resources/builds/Hamburger-testtag.apk

      - name: Setup Appium
        run: |
          npm install -g appium@next
          appium -v
          appium driver install uiautomator2
          appium driver list --installed
          nohup appium > /dev/null 2>&1 &

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd mobile-automation && mvn clean test